name: Build/release
on: push
jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ windows-latest ]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 16.13.0

      - name: Install dependencies
        run: |
          npm install fs fs/promises
          electron-builder -w

      #- name: Build/release Electron app
      #  uses: samuelmeuli/action-electron-builder@v1
      #  with:
      #    github_token: ${{ secrets.github_token }}

      - name: "Create Release"
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: false
          title: "Release v${{ steps.metadata.outputs.VERSION }}"
          files: |
            out/*.exe
            out/*.app
